name: artsee_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.5
  http: ^1.2.2

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/NotoSansSC-Regular.ttf

  fonts:
    # Noto Sans SC - 四元黑体风格
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.ttf
          weight: 400

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
